"use client";
import { useMemo, useState } from "react";
import { Bot, CheckCircle2, ChevronRight, Sparkles } from "lucide-react";

const fields = [["context","Контекст и потребность",20],["data","Данные и материалы",20],["result","Ожидаемый результат",15],["success","Критерии успеха",15],["constraints","Ограничения",10],["users","Пользователи",10],["contact","Связь с бизнесом",10]] as const;
const seeded = [
  {title:"Автоматизация записи клиентов",industry:"Ритейл",score:88,status:"Готовая",summary:"Снизить нагрузку на администраторов сети салонов."},
  {title:"Аналитика обращений жителей",industry:"GovTech",score:74,status:"Готовая",summary:"Классифицировать обращения и показать проблемные районы."},
  {title:"Помощник для первокурсников",industry:"EdTech",score:58,status:"Рабочая",summary:"Помочь студентам быстрее находить учебные сервисы."},
  {title:"Контроль остатков на складе",industry:"Логистика",score:36,status:"Черновик",summary:"Нужна прозрачность по критичным остаткам."},
];

export default function Home() {
  const [tab,setTab] = useState<"builder"|"catalog"|"proposals">("builder");
  const [draft,setDraft] = useState("Нужно улучшить запись клиентов в сеть салонов красоты: сейчас администраторы отвечают вручную в мессенджерах.");
  const [answers,setAnswers] = useState<Record<string,string>>({context:"",data:"",result:"",success:"",constraints:"",users:"",contact:""});
  const [published,setPublished] = useState(false);
  const score = useMemo(()=>fields.reduce((sum,[key,,points])=>sum+(answers[key]?.trim()?points:0),draft.trim()?20:0),[answers,draft]);
  const level = score>=90?"Приоритетная":score>=70?"Готовая":score>=40?"Рабочая":"Черновик";
  const nav = [["builder","Конструктор"],["catalog","Каталог"],["proposals","Отклики"]] as const;
  return <main className="min-h-screen bg-[#08151d] text-slate-100">
    <header className="border-b border-white/10 bg-[#0b1d27] px-5 py-4 lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><b className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7ff5a] text-[#0b1d27]">T</b><div><b className="text-lg">TaskLevel</b><p className="text-xs text-slate-400">Бизнес-задачи, готовые к работе</p></div></div><span className="rounded-full border border-white/10 px-3 py-2 text-sm">Алия · Бизнес</span></div></header>
    <div className="mx-auto grid max-w-7xl gap-7 px-5 py-7 lg:grid-cols-[210px_1fr] lg:px-10"><aside className="flex gap-2 overflow-x-auto lg:flex-col">{nav.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-3 text-left text-sm ${tab===id?"bg-[#e7ff5a] font-bold text-[#0b1d27]":"text-slate-300 hover:bg-white/5"}`}>{label}</button>)}<div className="mt-4 rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-4 text-xs text-cyan-100"><Sparkles className="mb-2 h-4 w-4"/>AI только подсказывает. Публикацию и выбор всегда подтверждает человек.</div></aside>
    {tab==="builder"&&<section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#e7ff5a]">Новая задача</p><h1 className="mt-1 text-3xl font-semibold">Превратите черновик в понятный бриф</h1></div><div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3"><p className="text-xs text-slate-400">Готовность задачи</p><b className="text-2xl text-[#e7ff5a]">{score}/100</b><span className="ml-2 text-sm">{level}</span></div></div><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-white/10 bg-[#102833] p-6"><label className="text-sm font-medium">Что нужно бизнесу?</label><textarea value={draft} onChange={e=>setDraft(e.target.value)} className="mt-3 min-h-32 w-full rounded-2xl border border-white/10 bg-[#08151d] p-4 text-sm outline-none focus:ring-2 focus:ring-[#e7ff5a]"/><button className="mt-4 flex gap-2 rounded-xl bg-[#e7ff5a] px-4 py-3 text-sm font-bold text-[#0b1d27]"><Bot className="h-4 w-4"/>Проанализировать с AI</button><div className="mt-7 border-t border-white/10 pt-5"><b>AI-уточняющие вопросы</b><div className="mt-4 space-y-3">{["Кто будет пользоваться решением и в какой момент?","Какие данные, примеры или доступы уже есть?","Как вы поймёте, что задача решена успешно?"].map((q,i)=><p key={q} className="rounded-xl bg-white/5 p-3 text-sm"><span className="mr-2 text-[#e7ff5a]">0{i+1}</span>{q}</p>)}</div></div></div><div className="rounded-3xl border border-white/10 bg-[#102833] p-6"><p className="text-sm font-medium">Карточка задачи</p><p className="mt-1 text-xs text-slate-400">Заполненные поля влияют на рейтинг.</p><div className="mt-4 space-y-3">{fields.map(([key,label,points])=><label key={key} className="block"><span className="flex justify-between text-xs text-slate-300">{label}<b className="text-[#e7ff5a]">+{points}</b></span><input value={answers[key]} onChange={e=>setAnswers({...answers,[key]:e.target.value})} placeholder="Добавьте информацию" className="mt-1 w-full rounded-lg border border-white/10 bg-[#08151d] px-3 py-2 text-sm outline-none focus:border-[#e7ff5a]"/></label>)}</div><button onClick={()=>setPublished(true)} className="mt-5 flex w-full justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#0b1d27]">{published?<><CheckCircle2 className="h-4 w-4"/>Опубликовано</>:"Подтвердить и опубликовать"}</button></div></div></section>}
    {tab==="catalog"&&<section><p className="text-sm text-[#e7ff5a]">Открытый каталог</p><h1 className="mt-1 text-3xl font-semibold">Задачи для студенческих команд</h1><div className="mt-6 grid gap-4 md:grid-cols-2">{[...(published?[{title:"Автоматизация записи клиентов",industry:"Ритейл",score,status:level,summary:draft}]:[]),...seeded].sort((a,b)=>b.score-a.score).map((task,i)=><article key={i} className="rounded-3xl border border-white/10 bg-[#102833] p-5"><div className="flex justify-between"><span className="rounded-full bg-white/8 px-3 py-1 text-xs">{task.industry}</span><b className="text-[#e7ff5a]">{task.score}/100</b></div><h2 className="mt-5 text-xl font-semibold">{task.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{task.summary}</p><div className="mt-5 flex justify-between text-sm"><span>{task.status}</span><button onClick={()=>setTab("proposals")} className="flex items-center gap-1 font-medium text-[#e7ff5a]">Откликнуться <ChevronRight className="h-4 w-4"/></button></div></article>)}</div></section>}
    {tab==="proposals"&&<section className="max-w-3xl"><p className="text-sm text-[#e7ff5a]">Отклик команды</p><h1 className="mt-1 text-3xl font-semibold">Предложите своё решение</h1><div className="mt-6 rounded-3xl border border-white/10 bg-[#102833] p-6"><input className="w-full rounded-xl border border-white/10 bg-[#08151d] px-4 py-3 text-sm" placeholder="Название команды" defaultValue="Pixel Pioneers"/><textarea className="mt-3 min-h-28 w-full rounded-xl border border-white/10 bg-[#08151d] p-4 text-sm" placeholder="Идея решения и план"/><input className="mt-3 w-full rounded-xl border border-white/10 bg-[#08151d] px-4 py-3 text-sm" placeholder="Ссылка на прототип"/><button className="mt-4 rounded-xl bg-[#e7ff5a] px-5 py-3 text-sm font-bold text-[#0b1d27]">Отправить предложение</button></div></section>}
    </div></main>;
}
