"use client";

import { useEffect, useMemo, useState } from "react";
import { Bot, CheckCircle2, ChevronRight, LogIn, Send, Sparkles, X } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001";
const fields = [["context","Контекст и потребность",20],["data","Данные и материалы",20],["expected_result","Ожидаемый результат",15],["success_criteria","Критерии успеха",15],["constraints","Ограничения",10],["users","Пользователи",10],["contact","Связь с бизнесом",10]] as const;
const fallbackTasks = [
  {id:0,title:"Автоматизация записи клиентов",industry:"Ритейл",score:88,context:"Снизить нагрузку на администраторов сети салонов."},
  {id:0,title:"Аналитика обращений жителей",industry:"GovTech",score:74,context:"Классифицировать обращения и показать проблемные районы."},
  {id:0,title:"Помощник для первокурсников",industry:"EdTech",score:58,context:"Помочь студентам быстрее находить учебные сервисы."},
];
type Task = typeof fallbackTasks[number] & {owner_id?:number; published?:boolean};
type User = {id:number;name:string;email:string;role:"business"|"student_team"};

export default function Home() {
  const [tab,setTab] = useState<"builder"|"catalog"|"proposals">("builder");
  const [draft,setDraft] = useState("Нужно улучшить запись клиентов в сеть салонов красоты: сейчас администраторы отвечают вручную в мессенджерах.");
  const [answers,setAnswers] = useState<Record<string,string>>({context:"",data:"",expected_result:"",success_criteria:"",constraints:"",users:"",contact:""});
  const [questions,setQuestions] = useState<string[]>(["Кто будет пользоваться решением и в какой момент?","Какие данные, примеры или доступы уже есть?","Как вы поймёте, что задача решена успешно?"]);
  const [tasks,setTasks] = useState<Task[]>(fallbackTasks); const [selected,setSelected] = useState<Task | null>(null);
  const [token,setToken] = useState(""); const [user,setUser] = useState<User | null>(null); const [notice,setNotice] = useState(""); const [loading,setLoading] = useState(false);
  const [authOpen,setAuthOpen] = useState(false); const [isRegister,setIsRegister] = useState(true); const [auth,setAuth] = useState({name:"",email:"",password:"",role:"business"});
  const [idea,setIdea] = useState(""); const [plan,setPlan] = useState(""); const [chat,setChat] = useState<{id:number;name:string;body:string}[]>([]); const [message,setMessage] = useState("");
  const score = useMemo(()=>fields.reduce((sum,[key,,points])=>sum+(answers[key]?.trim()?points:0),0),[answers]);
  const level = score>=90?"Приоритетная":score>=70?"Готовая":score>=40?"Рабочая":"Черновик";
  const headers = token ? {"Content-Type":"application/json",Authorization:`Bearer ${token}`} : {"Content-Type":"application/json"};
  const loadTasks = async () => { try { const r=await fetch(`${API}/api/tasks`); if(r.ok) setTasks(await r.json()); } catch {} };
  useEffect(()=>{loadTasks();},[]);
  const analyze = async () => { setLoading(true); try { const r=await fetch(`${API}/api/ai/clarify`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({draft})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setQuestions(data.questions); setNotice(data.source==="openai"?"AI подготовил вопросы по вашему черновику.":"Показаны базовые вопросы: добавьте OPENAI_API_KEY для AI-режима."); } catch(e) {setNotice(e instanceof Error?e.message:"Не удалось обратиться к API");} finally {setLoading(false);} };
  const authenticate = async () => { setLoading(true); try { const r=await fetch(`${API}/api/auth/${isRegister?"register":"login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(isRegister?auth:{email:auth.email,password:auth.password})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setToken(data.token); setUser(data.user); setAuthOpen(false); setNotice(`Вы вошли как ${data.user.name}.`); } catch(e) {setNotice(e instanceof Error?e.message:"Не удалось выполнить вход");} finally {setLoading(false);} };
  const publish = async () => { if(!token) return setAuthOpen(true); setLoading(true); try { const r=await fetch(`${API}/api/tasks`,{method:"POST",headers,body:JSON.stringify({title:"Автоматизация записи клиентов",industry:"Ритейл",...answers,interaction_format:"Онлайн",published:true})}); const data=await r.json(); if(!r.ok) throw new Error(data.error); setNotice(`Задача опубликована: ${data.score}/100.`); await loadTasks(); setTab("catalog"); } catch(e) {setNotice(e instanceof Error?e.message:"Не удалось опубликовать");} finally {setLoading(false);} };
  const openTask = async (task:Task) => { setSelected(task); setTab("proposals"); setChat([]); if(token&&task.id) {try {const r=await fetch(`${API}/api/tasks/${task.id}/messages`,{headers});if(r.ok)setChat(await r.json());}catch{}} };
  const propose = async () => { if(!selected?.id)return setNotice("Для живого отклика выберите задачу из Docker-каталога."); if(!token)return setAuthOpen(true); try {const r=await fetch(`${API}/api/tasks/${selected.id}/proposals`,{method:"POST",headers,body:JSON.stringify({idea,plan,timeline:"2 недели"})});const data=await r.json();if(!r.ok)throw new Error(data.error);setNotice("Отклик отправлен. Бизнес сам примет или отклонит его.");setIdea("");setPlan("");}catch(e){setNotice(e instanceof Error?e.message:"Не удалось отправить отклик");}};
  const sendMessage = async () => {if(!selected?.id||!message.trim()||!token)return;const r=await fetch(`${API}/api/tasks/${selected.id}/messages`,{method:"POST",headers,body:JSON.stringify({body:message})});if(r.ok){const item=await r.json();setChat([...chat,{...item,name:user?.name||"Вы"}]);setMessage("");}};
  const nav = [["builder","Конструктор"],["catalog","Каталог"],["proposals","Отклики и чат"]] as const;
  return <main className="min-h-screen bg-[#08151d] text-slate-100">
    <header className="border-b border-white/10 bg-[#0b1d27] px-5 py-4 lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><b className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7ff5a] text-[#0b1d27]">T</b><div><b className="text-lg">TaskLevel</b><p className="text-xs text-slate-400">Бизнес-задачи, готовые к работе</p></div></div><button onClick={()=>user?(setUser(null),setToken("")):setAuthOpen(true)} className="flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-sm"><LogIn className="h-4 w-4"/>{user?`${user.name} · ${user.role==="business"?"Бизнес":"Команда"}`:"Войти"}</button></div></header>
    <div className="mx-auto grid max-w-7xl gap-7 px-5 py-7 lg:grid-cols-[210px_1fr] lg:px-10"><aside className="flex gap-2 overflow-x-auto lg:flex-col">{nav.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-3 text-left text-sm ${tab===id?"bg-[#e7ff5a] font-bold text-[#0b1d27]":"text-slate-300 hover:bg-white/5"}`}>{label}</button>)}<div className="mt-4 rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-4 text-xs text-cyan-100"><Sparkles className="mb-2 h-4 w-4"/>AI только подсказывает. Публикацию и выбор всегда подтверждает человек.</div></aside>
    <section>{notice&&<div className="mb-5 rounded-xl border border-[#e7ff5a]/30 bg-[#e7ff5a]/10 p-3 text-sm text-[#f2ffc1]">{notice}</div>}
    {tab==="builder"&&<div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#e7ff5a]">Новая задача</p><h1 className="mt-1 text-3xl font-semibold">Превратите черновик в понятный бриф</h1></div><div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3"><p className="text-xs text-slate-400">Готовность задачи</p><b className="text-2xl text-[#e7ff5a]">{score}/100</b><span className="ml-2 text-sm">{level}</span></div></div><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-white/10 bg-[#102833] p-6"><label className="text-sm font-medium">Что нужно бизнесу?</label><textarea value={draft} onChange={e=>setDraft(e.target.value)} className="mt-3 min-h-32 w-full rounded-2xl border border-white/10 bg-[#08151d] p-4 text-sm outline-none focus:ring-2 focus:ring-[#e7ff5a]"/><button onClick={analyze} disabled={loading} className="mt-4 flex gap-2 rounded-xl bg-[#e7ff5a] px-4 py-3 text-sm font-bold text-[#0b1d27]"><Bot className="h-4 w-4"/>{loading?"Анализируем…":"Проанализировать с AI"}</button><div className="mt-7 border-t border-white/10 pt-5"><b>AI-уточняющие вопросы</b><div className="mt-4 space-y-3">{questions.map((q,i)=><p key={q} className="rounded-xl bg-white/5 p-3 text-sm"><span className="mr-2 text-[#e7ff5a]">0{i+1}</span>{q}</p>)}</div></div></div><div className="rounded-3xl border border-white/10 bg-[#102833] p-6"><p className="text-sm font-medium">Карточка задачи</p><p className="mt-1 text-xs text-slate-400">Заполненные поля влияют на рейтинг.</p><div className="mt-4 space-y-3">{fields.map(([key,label,points])=><label key={key} className="block"><span className="flex justify-between text-xs text-slate-300">{label}<b className="text-[#e7ff5a]">+{points}</b></span><input value={answers[key]} onChange={e=>setAnswers({...answers,[key]:e.target.value})} placeholder="Добавьте информацию" className="mt-1 w-full rounded-lg border border-white/10 bg-[#08151d] px-3 py-2 text-sm outline-none focus:border-[#e7ff5a]"/></label>)}</div><button onClick={publish} className="mt-5 flex w-full justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#0b1d27]"><CheckCircle2 className="h-4 w-4"/>Подтвердить и опубликовать</button></div></div></div>}
    {tab==="catalog"&&<div><p className="text-sm text-[#e7ff5a]">Открытый каталог</p><h1 className="mt-1 text-3xl font-semibold">Задачи для студенческих команд</h1><p className="mt-2 text-sm text-slate-400">Сортировка по прозрачному рейтингу готовности.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{[...tasks].sort((a,b)=>b.score-a.score).map((task,i)=><article key={`${task.id}-${i}`} className="rounded-3xl border border-white/10 bg-[#102833] p-5"><div className="flex justify-between"><span className="rounded-full bg-white/8 px-3 py-1 text-xs">{task.industry}</span><b className="text-[#e7ff5a]">{task.score}/100</b></div><h2 className="mt-5 text-xl font-semibold">{task.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{task.context}</p><button onClick={()=>openTask(task)} className="mt-5 flex items-center gap-1 font-medium text-[#e7ff5a]">Открыть задачу <ChevronRight className="h-4 w-4"/></button></article>)}</div></div>}
    {tab==="proposals"&&<div className="grid gap-6 xl:grid-cols-2"><div><p className="text-sm text-[#e7ff5a]">Отклик команды</p><h1 className="mt-1 text-3xl font-semibold">{selected?selected.title:"Выберите задачу в каталоге"}</h1><div className="mt-6 rounded-3xl border border-white/10 bg-[#102833] p-6"><textarea value={idea} onChange={e=>setIdea(e.target.value)} className="min-h-24 w-full rounded-xl border border-white/10 bg-[#08151d] p-4 text-sm" placeholder="Идея решения"/><textarea value={plan} onChange={e=>setPlan(e.target.value)} className="mt-3 min-h-24 w-full rounded-xl border border-white/10 bg-[#08151d] p-4 text-sm" placeholder="План реализации"/><button onClick={propose} className="mt-4 rounded-xl bg-[#e7ff5a] px-5 py-3 text-sm font-bold text-[#0b1d27]">Отправить предложение</button><p className="mt-3 text-xs text-slate-400">Отклик может отправить аккаунт с ролью «Команда».</p></div></div><div className="rounded-3xl border border-white/10 bg-[#102833] p-6"><p className="font-medium">Чат по задаче</p><div className="mt-4 min-h-48 space-y-3">{chat.length?chat.map(item=><div key={item.id} className="rounded-xl bg-white/5 p-3 text-sm"><b className="text-[#e7ff5a]">{item.name}</b><p className="mt-1">{item.body}</p></div>):<p className="text-sm text-slate-400">Войдите и откройте задачу, чтобы начать переписку.</p>}</div><div className="mt-4 flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#08151d] px-3 py-2 text-sm" placeholder="Напишите сообщение"/><button onClick={sendMessage} className="rounded-xl bg-white px-3 text-[#0b1d27]"><Send className="h-4 w-4"/></button></div></div></div>}
    </section></div>
    {authOpen&&<div className="fixed inset-0 grid place-items-center bg-black/60 p-4"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#102833] p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-semibold">{isRegister?"Создать аккаунт":"Войти"}</h2><button onClick={()=>setAuthOpen(false)}><X/></button></div>{isRegister&&<input value={auth.name} onChange={e=>setAuth({...auth,name:e.target.value})} className="mt-5 w-full rounded-xl bg-[#08151d] p-3 text-sm" placeholder="Имя или название команды"/>}<input value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})} className="mt-3 w-full rounded-xl bg-[#08151d] p-3 text-sm" placeholder="Email"/><input value={auth.password} type="password" onChange={e=>setAuth({...auth,password:e.target.value})} className="mt-3 w-full rounded-xl bg-[#08151d] p-3 text-sm" placeholder="Пароль"/>{isRegister&&<select value={auth.role} onChange={e=>setAuth({...auth,role:e.target.value})} className="mt-3 w-full rounded-xl bg-[#08151d] p-3 text-sm"><option value="business">Бизнес</option><option value="student_team">Студенческая команда</option></select>}<button onClick={authenticate} className="mt-5 w-full rounded-xl bg-[#e7ff5a] p-3 font-bold text-[#0b1d27]">{isRegister?"Зарегистрироваться":"Войти"}</button><button onClick={()=>setIsRegister(!isRegister)} className="mt-4 text-sm text-[#e7ff5a]">{isRegister?"Уже есть аккаунт? Войти":"Нет аккаунта? Зарегистрироваться"}</button></div></div>}
  </main>;
}
